### ISSUE TITLE
Module backen d'article

### ISSUE THREAD

**Issue by tiffan-source** [Alitcha-project/kumaa_api#2]
- [x] Système de migration
- [x] Système de seeding
- [x] tests unitaires
- [ ] Définitions des routes CRUD
- [ ] fonctions des contrôleurs
- [ ] fonctions modèles

L'architecture à adopter pour un module est la même que celle pour le module déjà présent.

**Comment by Alchrist-master** [comment]
En quoi consiste le Système de migration  svp?

**Comment by tiffan-source** [comment]
Le système de migration nous permet de construire progressivement la base de donnée. Afin d'avoir à tous les niveaux une même base de donne et de s'assurer qu'une modification de la base de donnée entraine également une modification chez tout le monde, nous utilisons Phinx qui est un outil de migration de base de donnée
---
Phinx permet aux développeurs de modifier et de manipuler les bases de données de manière claire et concise. Il évite d'écrire du SQL à la main et offre plutôt une puissante API pour créer des migrations à l'aide de code PHP. Les développeurs peuvent ensuite versionner ces migrations à l'aide de leur système SCM préféré. Cela rend les migrations Phinx portables entre différents systèmes de bases de données. Phinx conserve la trace des migrations exécutées, de sorte que vous pouvez moins vous soucier de l'état de votre base de données et vous concentrer sur la création de meilleurs logiciels.
---


https://book.cakephp.org/phinx/0/en/index.html

## Comment le mettre en place dans chaque module ?

Il faut créer pour chaque module, un dossier `db` avec à l'intérieur un dossier `seed` et un dossier `migration`. Dans la class du Module configurer le chemin de vers les dossiers `seed` et `migration` a l'aide des variables globales `MIGRATION` et `SEED`

```
class Article extends Module
{
    const MIGRATION = __DIR__ . '/db/migration';
    const SEED = __DIR__ . '/db/seeds';
}
``` 

Rajoutez cette configuration dans le fichier phinx.php 

```
$migration = [
    \Kumaa\Modules\Article\Article::MIGRATION
];

$seed = [
    \Kumaa\Modules\Article\Article::SEED
];

```

**Comment by Alchrist-master** [comment]
Système de migration déjà fait,

**Comment by Alchrist-master** [comment]
Système de seeding consiste en quoi ?

**Comment by tiffan-source** [comment]
Le seeding est un système permettant de préremplir la base de donne afin d'avoir des données de départ. Nous utilisons toujours Phinx qui propose un tel système. Par ailleurs, Faker nous permet de générer de fausses donnes de différent type.

https://book.cakephp.org/phinx/0/en/seeding.html
https://fakerphp.github.io/

Exemple
```
<?php

use Phinx\Seed\AbstractSeed;
use Faker\Factory;

/**
 * AddArticle
 */
class AddArticle extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run(): void
    {
        $data = [];

        $faker = Factory::create("fr_FR");
        $date = $faker->unixTime('now');
        

        for ($i=0; $i < 100; $i++) {
            $data[] = [
                "title_article" => $faker->sentence(),
                "text_article" => $faker->text(),
                "date_post_article" => date('Y-m-d H:i:s', $date),
                "date_edit_article" => date('Y-m-d H:i:s', $date),
            ];
        }

        $this->table('articles')
            ->insert($data)
            ->saveData();
    }
}

```
